// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyobpbiyybcveplktryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b2JwYml5eWJjdmVwbGt0cnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTA1NDUsImV4cCI6MjA2MjEyNjU0NX0.lxfWqO3jqHV4kPkJLOYZZr5WTlS2vK6a4NdKolBHsUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);